<a href="https://colab.research.google.com/github/NavjyotDataScientist/kaggle_huggingface_universe_projects/blob/main/6_1_multiclass_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Binary:

2 classes → 0 or 1

Uses Sigmoid

Multiclass:

More than 2 classes (0, 1, 2, 3 …)

Uses Softmax

👉 Same idea, different probability function.


In [1]:
# 1️⃣ Imports
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# 2️⃣ Load dataset (3 classes)
X, y = load_iris(return_X_y=True)

# 3️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# 4️⃣ Model
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# 5️⃣ Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

# 6️⃣ Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 7️⃣ Sample probability output
print("Sample predicted probabilities:\n", y_prob[:3])


Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Sample predicted probabilities:
 [[4.09968242e-03 8.12343795e-01 1.83556522e-01]
 [9.41955384e-01 5.80440355e-02 5.80206806e-07]
 [1.58411237e-08 2.09129768e-03 9.97908686e-01]]
